package com.example.day03.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.day03.bean.Good;

import com.example.day03.dao.GoodDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodDaoConfig;

    private final GoodDao goodDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodDaoConfig = daoConfigMap.get(GoodDao.class).clone();
        goodDaoConfig.initIdentityScope(type);

        goodDao = new GoodDao(goodDaoConfig, this);

        registerDao(Good.class, goodDao);
    }
    
    public void clear() {
        goodDaoConfig.clearIdentityScope();
    }

    public GoodDao getGoodDao() {
        return goodDao;
    }

}
